openapi: 3.0.0
info:
  description: |
    SIH Backend Server Documentation
  version: "1.0.0"
  title: SIH-Backend
  contact:
    email: raghhavdturki@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: Development Server
    url: http://localhost:7071/api/
  - description: Production Server
    url: https://sih-2022-server.azurewebsites.net/api/
  - description: Chat Server
    url: https://sih-email.herokuapp.com/api/chat
paths:
  /createAdmin:
    post: 
      tags:
        - admin
      summary: Create Admin Account
      operationId: createAdmin
      requestBody:
        $ref: '#/components/requestBodies/CreateAdminInput'
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: Admin Created Successfully
  /createEmployee:
    post: 
      tags:
        - admin
      security: 
        - bearerAuth: []
      summary: Create Employee Account
      operationId: createEmployee
      requestBody:
        $ref: '#/components/requestBodies/CreateEmployeeInput'
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: Employee Created Successfully
  /createHOD:
    post: 
      tags:
        - admin
      security: 
        - bearerAuth: []
      summary: Create HOD Account
      operationId: createHOD
      requestBody:
        $ref: '#/components/requestBodies/CreateEmployeeInput'
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: HOD Created Successfully
  /login:
    post:
      tags: 
        - login
      summary: Login
      operationId: login
      requestBody:
        $ref: '#/components/requestBodies/LoginInput'
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: Logged In Successfully!
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/LoginResponse'
  /uploadFile:
    post:
      tags:
        - employee
      security: 
        - bearerAuth: []
      summary: Upload File
      operationId: uploadFile
      parameters: 
        - in: query
          name: filename
          description: filename
          schema:
            type: string
          required: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                    type: string
                    format: binary
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: File Uploaded Successfully
          content:
            application/json:
              schema:
                properties:
                  url:
                    type: string
  /createDocument:
    post:
      tags:
        - employee
      security: 
        - bearerAuth: []
      summary: Create Document
      operationId: createDocument
      requestBody:
        $ref: '#/components/requestBodies/CreateDocumentInput'
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: Document Created Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDocumentResponse'
  /rooms:
    get:
      tags:
        - chat
      security:
       - bearerAuth: []
      summary: Fetch all the rooms the employee is a part of
      operationId: rooms
      parameters: 
        - in: query
          name: employeeId
          schema:
            type: string
          required: true
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: Rooms fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRoomsResponse'
  /messages:
    get:
      tags:
        - chat
      security:
        - bearerAuth: []
      summary: Fetch all the messages in a room
      operationId: messages
      parameters: 
        - in: query
          name: roomId
          schema:
            type: string
          required: true
      responses:
        '400':
          description: Invalid input
        '500':
          description: Internal Server Error
        '200':
          description: Messages fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessagesResponse'
components:
  schemas:
    Employee:
      type: object
      properties:
        name:
          type: string
        employeeID:
          type: string
        email:
          type: string
        gender:
          type: string
        dob:
          type: string
          format: date-time
        address:
          type: string
        password:
          type: string
        role: 
          type: string
        department:
          type: string
        profile:
          type: object
          properties:
            name:
              type: string
            employeeID:
              type: string
            email:
              type: string
            gender:
              type: string
            dob:
              type: string
              format: date-time
            address:
              type: string
            role: 
              type: string
            department:
              type: string
    Admin:
      type: object
      properties:
        name:
          type: string
        employeeID:
          type: string
        email:
          type: string
        gender:
          type: string
        dob:
          type: string
          format: date-time
        address:
          type: string
        password:
          type: string
        role: 
          type: string
        department:
          type: string
        profile:
          type: object
          properties:
            name:
              type: string
            employeeID:
              type: string
            email:
              type: string
            gender:
              type: string
            dob:
              type: string
              format: date-time
            address:
              type: string
            role: 
              type: string
            department:
              type: string 
    Conversation:
      type: object
      properties:
        conversationName:
          type: string
        documentId:
          type: string
        participants:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              info:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
    Message:
      type: object
      properties:
        senderId:
          type: string
        subject:
          type: string
        content:
          type: string
        conversationId:
          type: string
        senderName: 
          type: string
    CreateAdminInput:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        address:
          type: string
        gender:
          type: string
        dob:
          type: string
          format: date-time
        department:
          type: string
    CreateEmployeeInput:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        gender:
          type: string
        dob:
          type: string
          format: date-time
        department:
          type: string
        personalEmail: 
          type: string
    LoginInput:
      type: object
      properties:
        employeeId:
          type: string
        password:
          type: string
        role: 
          type: string
          enum:
            - admin
            - employee
            - hod
    CreateDocumentInput:
      type: object
      properties:
        employeeId: 
          type: string
        employee_name: 
          type: string
        subject: 
          type: string
        description: 
          type: string
        main_file: 
          type: array
          items:
            type: string
        reference_file:
          type: array
          items:
            type: string
        forwarding_dept: 
          type: string
        category: 
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        profile:
          type: object
    CreateDocumentResponse:
      type: object
      properties: 
        documentId: 
          type: string
        employeeId: 
          type: string
        roomId: 
          type: string
    GetRoomsResponse:
      type: array
      items:
        $ref: "#/components/schemas/Conversation"
    GetMessagesResponse:
      type: array
      items:
        $ref: "#/components/schemas/Message"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Iron Sealed Token
  requestBodies:
    CreateAdminInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateAdminInput'
        application/xml:
          schema:
            $ref: '#/components/schemas/CreateAdminInput'
      required: true
    CreateEmployeeInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateEmployeeInput'
        application/xml:
          schema:
            $ref: '#/components/schemas/CreateEmployeeInput'
      required: true
    LoginInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginInput'
        application/xml:
          schema:
            $ref: '#/components/schemas/LoginInput'
      required: true
    CreateDocumentInput:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateDocumentInput'
        application/xml:
          schema:
            $ref: '#/components/schemas/CreateDocumentInput'
      required: true